import {
  ArrowRight,
  CircleGauge,
  Landmark,
  ShieldCheck,
  TrendingUp,
  WalletCards,
} from 'lucide-react';
import { formatFinanceMoney } from '@/lib/finance/format';
import { buildMonthlyProfitCenter } from '@/lib/finance/profitCenter';
import type { FinanceRecord } from '@/lib/queries/useFinanceStateFlow';

export const dynamic = 'force-dynamic';

const scope = {
  tenant_id: 'preview',
  company_id: 'preview',
  owner_kind: 'company' as const,
};

function record(id: string, classification: string, amount: string): FinanceRecord {
  return {
    id,
    scope,
    classification,
    effective_at: '2026-10-06T12:00:00+02:00',
    postings: [{
      id: `${id}-cash`,
      account_id: 'preview-cash',
      ledger_code: 'cash:preview-cash',
      amount: { value: amount, currency: 'EUR', scale: 2 },
    }],
    corrections: [],
  };
}

const previewRecords: FinanceRecord[] = [
  record('customer-cash', 'customer_receipt', '1850.00'),
  record('operating-costs', 'operating_expense', '-1120.00'),
  record('founder-capital', 'founder_funding', '500.00'),
];

function Tile({
  label,
  value,
  note,
  accent = false,
}: {
  label: string;
  value: string;
  note: string;
  accent?: boolean;
}) {
  return (
    <div className={`rounded-[22px] border p-4 ${accent
      ? 'border-emerald-300/15 bg-emerald-400/[0.045]'
      : 'border-white/[0.07] bg-white/[0.02]'}`}>
      <div className="text-[9px] uppercase tracking-[0.17em] text-white/30">{label}</div>
      <div className="mt-2 text-xl font-medium tracking-[-0.035em] text-white/86">{value}</div>
      <div className="mt-1 text-[9px] leading-relaxed text-white/30">{note}</div>
    </div>
  );
}

export default function ProfitCenterPreview() {
  const snapshot = buildMonthlyProfitCenter(previewRecords, {
    now: new Date('2026-10-06T18:00:00+02:00'),
    hasOlderRecords: false,
  });

  return (
    <main className="min-h-screen bg-[#090714] px-4 py-5 text-white">
      <div className="mx-auto w-full max-w-md space-y-4">
        <section className="rounded-[28px] border border-amber-300/12 bg-amber-400/[0.035] p-4">
          <div className="text-[9px] uppercase tracking-[0.2em] text-amber-100/52">Illustrative product preview</div>
          <p className="mt-2 text-[11px] leading-relaxed text-amber-50/58">
            Diese drei EUR-Zahlen sind bewusst Beispielwerte, keine echten SAIMÔR-Buchungsdaten. Die Budget- und Risk-Logik ist dieselbe wie in PR #99.
          </p>
        </section>

        <header className="rounded-[30px] border border-emerald-300/10 bg-[radial-gradient(circle_at_top_right,rgba(16,185,129,0.14),transparent_36%),rgba(255,255,255,0.02)] p-5 shadow-2xl">
          <div className="flex items-center gap-2 text-[9px] uppercase tracking-[0.24em] text-emerald-100/42">
            <CircleGauge size={11} /> SAIMÔR Finance · Profit Center
          </div>
          <h1 className="mt-3 text-[28px] font-medium tracking-[-0.05em] text-white/92">Capital generated by Finance</h1>
          <p className="mt-2 text-[11px] leading-relaxed text-white/36">
            Protect → Understand → Grow. Kapital wird getrennt nach Betrieb, Treasury, Yield/Liquidity und Trading geführt.
          </p>
        </header>

        <section className="grid grid-cols-2 gap-3">
          <Tile
            label="Customer cash in"
            value={formatFinanceMoney(snapshot.customerReceipts)}
            note="Noch keine Revenue Recognition."
          />
          <Tile
            label="Operating cash out"
            value={formatFinanceMoney(snapshot.operatingExpenses)}
            note="Belegter operativer Abfluss."
          />
          <Tile
            label="Operating cash result"
            value={formatFinanceMoney(snapshot.operatingCashResult)}
            note="Cash-Ergebnis, kein Jahresabschluss."
            accent
          />
          <Tile
            label="Founder funding"
            value={formatFinanceMoney(snapshot.founderFunding)}
            note="Kapitalzufuhr, keine Performance."
          />
        </section>

        <section className="rounded-[26px] border border-violet-300/10 bg-[radial-gradient(circle_at_top_right,rgba(139,92,246,0.10),transparent_38%),rgba(255,255,255,0.018)] p-5">
          <div className="flex items-center gap-2 text-[9px] uppercase tracking-[0.2em] text-violet-100/42">
            <WalletCards size={11} /> Monthly capital mandate
          </div>
          <div className="mt-4 space-y-3">
            {[
              ['Operating Cash', 'PROTECT', 'Rechnungen, Steuer, Reserve. Kein Trading-Kapital.'],
              ['XRP Sovereign Treasury', 'RESERVE', 'Strategischer Bestand, getrennt vom Trading Desk.'],
              ['XRPL Yield / Liquidity', 'RESEARCH', 'AMM/Spread erst nach messbarer Netto-Rendite.'],
              ['Trading Desk', 'DRAFT', 'Eigenes Monatsbudget, harte Verlustgrenzen, manuelle Freigabe.'],
            ].map(([title, status, copy]) => (
              <div key={title} className="rounded-2xl border border-white/[0.06] bg-black/15 p-4">
                <div className="flex items-center justify-between gap-3">
                  <div className="text-[12px] font-medium text-white/74">{title}</div>
                  <span className="rounded-full border border-white/[0.07] px-2 py-1 text-[8px] tracking-[0.14em] text-white/38">{status}</span>
                </div>
                <div className="mt-2 text-[10px] leading-relaxed text-white/30">{copy}</div>
              </div>
            ))}
          </div>
        </section>

        <section className="rounded-[26px] border border-white/[0.07] bg-black/15 p-5">
          <div className="flex items-center gap-2 text-[9px] uppercase tracking-[0.2em] text-white/32">
            <ShieldCheck size={11} /> Draft trading policy
          </div>
          <div className="mt-4 space-y-3 text-[11px]">
            <div className="flex items-center justify-between border-b border-white/[0.05] pb-3">
              <span className="text-white/38">Monthly trading budget</span>
              <span className="font-medium text-white/82">{formatFinanceMoney(snapshot.draftTradingBudget)}</span>
            </div>
            <div className="flex items-center justify-between border-b border-white/[0.05] pb-3">
              <span className="text-white/38">Monthly loss stop</span>
              <span className="font-medium text-white/70">{formatFinanceMoney(snapshot.draftMonthlyLossStop)}</span>
            </div>
            <div className="flex items-center justify-between border-b border-white/[0.05] pb-3">
              <span className="text-white/38">Risk / trade</span>
              <span className="font-medium text-white/70">{formatFinanceMoney(snapshot.draftPerTradeRisk)}</span>
            </div>
            <div className="flex items-center justify-between">
              <span className="text-white/38">Execution</span>
              <span className="text-[9px] uppercase tracking-[0.14em] text-emerald-100/62">Manual · no leverage</span>
            </div>
          </div>
        </section>

        <section className="grid gap-3">
          <div className="rounded-[22px] border border-white/[0.07] bg-white/[0.018] p-4">
            <div className="flex items-center gap-2 text-[9px] uppercase tracking-[0.17em] text-white/30">
              <TrendingUp size={11} /> Finance-generated profit
            </div>
            <div className="mt-2 text-lg font-medium text-white/64">Attribution kommt als nächster CORE-Vertrag</div>
            <p className="mt-1 text-[9px] leading-relaxed text-white/28">
              Trading P&L, Liquidity Fees, Treasury-Ertrag und echte Revenue-Effekte werden später getrennt realisiert und gemessen.
            </p>
          </div>

          <div className="rounded-[22px] border border-cyan-300/[0.08] bg-cyan-400/[0.02] p-4">
            <div className="flex items-center gap-2 text-[9px] uppercase tracking-[0.17em] text-cyan-100/36">
              <Landmark size={11} /> Next
            </div>
            <div className="mt-2 flex items-center justify-between gap-3">
              <div className="text-sm font-medium text-white/72">Persistente Budget-Policy in CORE</div>
              <ArrowRight size={14} className="text-cyan-100/48" />
            </div>
          </div>
        </section>
      </div>
    </main>
  );
}
