FROM node:20-alpine AS base

WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1

# Dependencies
FROM base AS deps
ENV NODE_ENV=development
COPY package.json package-lock.json* ./
RUN npm ci --legacy-peer-deps

# Build
FROM base AS build
ARG NEXT_PUBLIC_CORE_API_URL
ARG NEXT_PUBLIC_CORE_WS_URL
ARG NEXT_PUBLIC_SAIMOR_CORE_URL
ARG NEXT_PUBLIC_ALLOW_TOOL_EXECUTION
ARG NEXT_PUBLIC_DISABLE_WEBGL

# Next.js bakes NEXT_PUBLIC_* env vars into the client bundle at build time.
ENV NEXT_PUBLIC_CORE_API_URL=${NEXT_PUBLIC_CORE_API_URL}
ENV NEXT_PUBLIC_CORE_WS_URL=${NEXT_PUBLIC_CORE_WS_URL}
ENV NEXT_PUBLIC_SAIMOR_CORE_URL=${NEXT_PUBLIC_SAIMOR_CORE_URL}
ENV NEXT_PUBLIC_ALLOW_TOOL_EXECUTION=${NEXT_PUBLIC_ALLOW_TOOL_EXECUTION}
ENV NEXT_PUBLIC_DISABLE_WEBGL=${NEXT_PUBLIC_DISABLE_WEBGL}

COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

# Runtime
FROM base AS runner
ARG NEXT_PUBLIC_CORE_API_URL
ARG NEXT_PUBLIC_CORE_WS_URL
ARG NEXT_PUBLIC_SAIMOR_CORE_URL
ARG NEXT_PUBLIC_ALLOW_TOOL_EXECUTION
ARG NEXT_PUBLIC_DISABLE_WEBGL

ENV NEXT_PUBLIC_CORE_API_URL=${NEXT_PUBLIC_CORE_API_URL}
ENV NEXT_PUBLIC_CORE_WS_URL=${NEXT_PUBLIC_CORE_WS_URL}
ENV NEXT_PUBLIC_SAIMOR_CORE_URL=${NEXT_PUBLIC_SAIMOR_CORE_URL}
ENV NEXT_PUBLIC_ALLOW_TOOL_EXECUTION=${NEXT_PUBLIC_ALLOW_TOOL_EXECUTION}
ENV NEXT_PUBLIC_DISABLE_WEBGL=${NEXT_PUBLIC_DISABLE_WEBGL}

# NextAuth runtime config - MUST be set at runtime via docker run -e or docker-compose
# NEXTAUTH_URL=https://hq.saimor.world
# NEXTAUTH_SECRET=<secure-random-string>
# SAIMOR_CORE_URL=http://core:8081

ENV NODE_ENV=production
RUN addgroup -g 1001 -S nodejs && adduser -S nextjs -u 1001
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/public ./public
COPY --from=build /app/.next ./.next

USER nextjs
EXPOSE 3000
CMD ["npm", "run", "start"]
