FROM node:20-alpine AS base

WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1

# Dependencies
FROM base AS deps
ENV NODE_ENV=development
COPY package.json package-lock.json* ./
RUN npm ci --legacy-peer-deps

# Build
# IMPORTANT: Next.js bakes NEXT_PUBLIC_* vars into the client bundle at build time.
# Every NEXT_PUBLIC_* variable MUST be declared as ARG here and set as ENV before
# `npm run build`. Omitting one here means it will be undefined in production,
# even if passed at `docker run` time.
FROM base AS build
ARG NEXT_PUBLIC_CORE_API_URL
ARG NEXT_PUBLIC_CORE_WS_URL
ARG NEXT_PUBLIC_SAIMOR_CORE_URL
ARG NEXT_PUBLIC_ALLOW_TOOL_EXECUTION
ARG NEXT_PUBLIC_DISABLE_WEBGL
ARG NEXT_PUBLIC_SURFACE_MODE
ARG NEXT_PUBLIC_PADDLE_CLIENT_TOKEN
ARG NEXT_PUBLIC_PADDLE_ENV
ARG NEXT_PUBLIC_SAIMOR_CANARY_XRPL_ADDRESS
# Real Mora phase flags (P1-P5b)
ARG NEXT_PUBLIC_MORA_PERCEIVE_V1
ARG NEXT_PUBLIC_MORA_DIALOGUE_V1
ARG NEXT_PUBLIC_MORA_LIVE_V1

ENV NEXT_PUBLIC_CORE_API_URL=${NEXT_PUBLIC_CORE_API_URL}
ENV NEXT_PUBLIC_CORE_WS_URL=${NEXT_PUBLIC_CORE_WS_URL}
ENV NEXT_PUBLIC_SAIMOR_CORE_URL=${NEXT_PUBLIC_SAIMOR_CORE_URL}
ENV NEXT_PUBLIC_ALLOW_TOOL_EXECUTION=${NEXT_PUBLIC_ALLOW_TOOL_EXECUTION}
ENV NEXT_PUBLIC_DISABLE_WEBGL=${NEXT_PUBLIC_DISABLE_WEBGL}
ENV NEXT_PUBLIC_SURFACE_MODE=${NEXT_PUBLIC_SURFACE_MODE}
ENV NEXT_PUBLIC_PADDLE_CLIENT_TOKEN=${NEXT_PUBLIC_PADDLE_CLIENT_TOKEN}
ENV NEXT_PUBLIC_PADDLE_ENV=${NEXT_PUBLIC_PADDLE_ENV}
ENV NEXT_PUBLIC_SAIMOR_CANARY_XRPL_ADDRESS=${NEXT_PUBLIC_SAIMOR_CANARY_XRPL_ADDRESS}
ENV NEXT_PUBLIC_MORA_PERCEIVE_V1=${NEXT_PUBLIC_MORA_PERCEIVE_V1}
ENV NEXT_PUBLIC_MORA_DIALOGUE_V1=${NEXT_PUBLIC_MORA_DIALOGUE_V1}
ENV NEXT_PUBLIC_MORA_LIVE_V1=${NEXT_PUBLIC_MORA_LIVE_V1}

COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

# Runtime
FROM base AS runner
ARG NEXT_PUBLIC_CORE_API_URL
ARG NEXT_PUBLIC_CORE_WS_URL
ARG NEXT_PUBLIC_SAIMOR_CORE_URL
ARG NEXT_PUBLIC_ALLOW_TOOL_EXECUTION
ARG NEXT_PUBLIC_DISABLE_WEBGL
ARG NEXT_PUBLIC_SURFACE_MODE
ARG NEXT_PUBLIC_PADDLE_CLIENT_TOKEN
ARG NEXT_PUBLIC_PADDLE_ENV
ARG NEXT_PUBLIC_SAIMOR_CANARY_XRPL_ADDRESS
ARG NEXT_PUBLIC_MORA_PERCEIVE_V1
ARG NEXT_PUBLIC_MORA_DIALOGUE_V1
ARG NEXT_PUBLIC_MORA_LIVE_V1

ENV NEXT_PUBLIC_CORE_API_URL=${NEXT_PUBLIC_CORE_API_URL}
ENV NEXT_PUBLIC_CORE_WS_URL=${NEXT_PUBLIC_CORE_WS_URL}
ENV NEXT_PUBLIC_SAIMOR_CORE_URL=${NEXT_PUBLIC_SAIMOR_CORE_URL}
ENV NEXT_PUBLIC_ALLOW_TOOL_EXECUTION=${NEXT_PUBLIC_ALLOW_TOOL_EXECUTION}
ENV NEXT_PUBLIC_DISABLE_WEBGL=${NEXT_PUBLIC_DISABLE_WEBGL}
ENV NEXT_PUBLIC_SURFACE_MODE=${NEXT_PUBLIC_SURFACE_MODE}
ENV NEXT_PUBLIC_PADDLE_CLIENT_TOKEN=${NEXT_PUBLIC_PADDLE_CLIENT_TOKEN}
ENV NEXT_PUBLIC_PADDLE_ENV=${NEXT_PUBLIC_PADDLE_ENV}
ENV NEXT_PUBLIC_SAIMOR_CANARY_XRPL_ADDRESS=${NEXT_PUBLIC_SAIMOR_CANARY_XRPL_ADDRESS}
ENV NEXT_PUBLIC_MORA_PERCEIVE_V1=${NEXT_PUBLIC_MORA_PERCEIVE_V1}
ENV NEXT_PUBLIC_MORA_DIALOGUE_V1=${NEXT_PUBLIC_MORA_DIALOGUE_V1}
ENV NEXT_PUBLIC_MORA_LIVE_V1=${NEXT_PUBLIC_MORA_LIVE_V1}

# NextAuth + Core URL — MUST be set at runtime via docker run -e or docker-compose:
# NEXTAUTH_URL=https://hq.saimor.world
# NEXTAUTH_SECRET=<secure-random-string>
# SAIMOR_CORE_URL=http://core:8081

ENV NODE_ENV=production
RUN addgroup -g 1001 -S nodejs && adduser -S nextjs -u 1001
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/public ./public
COPY --from=build /app/.next ./.next

USER nextjs
EXPOSE 3000
CMD ["npm", "run", "start"]
