import type { AppManifest } from './types';

export const APP_REGISTRY: AppManifest[] = [
  // ── Core ──────────────────────────────────────────────────────────────────
  {
    id: 'finder',
    name: 'Finder',
    description: 'Dateien und Ordner durchsuchen',
    icon: 'Folder',
    color: 'blue',
    category: 'core',
    defaultSize: { width: 900, height: 620 },
  },
  {
    id: 'document',
    name: 'Dokument',
    description: 'Dokumente öffnen und lesen',
    icon: 'FileText',
    color: 'slate',
    category: 'core',
    defaultSize: { width: 720, height: 560 },
  },
  {
    id: 'website-dossier',
    name: 'Website Dossier',
    description: 'Security-Check aus WORLD als HQ-Arbeitsobjekt',
    icon: 'ShieldCheck',
    color: 'teal',
    category: 'core',
    defaultSize: { width: 1040, height: 720 },
  },
  {
    id: 'notes',
    name: 'Notizen',
    description: 'Persönliche Notizen',
    icon: 'StickyNote',
    color: 'amber',
    category: 'core',
    defaultSize: { width: 480, height: 420 },
    singleton: true,
  },
  {
    id: 'grid',
    name: 'Alle Inhalte',
    description: 'Alle Knoten in der Übersicht',
    icon: 'Grid',
    color: 'green',
    category: 'core',
    defaultSize: { width: 900, height: 640 },
  },
  {
    id: 'finance',
    name: 'Capital',
    description: 'Wallets, Vermögen und On-chain-Kapital — zuerst read-only',
    icon: 'Activity',
    color: 'green',
    category: 'core',
    defaultSize: { width: 980, height: 720 },
    singleton: true,
    isNew: true,
  },

  // ── Intelligence ──────────────────────────────────────────────────────────
  {
    id: 'chat',
    name: 'Chat',
    description: 'Mit Mora sprechen',
    icon: 'MessageCircle',
    color: 'purple',
    category: 'intelligence',
    defaultSize: { width: 860, height: 680 },
  },
  {
    id: 'scanner',
    name: 'Scanner',
    description: 'Dateien hochladen und kategorisieren',
    icon: 'ScanLine',
    color: 'teal',
    category: 'intelligence',
    defaultSize: { width: 840, height: 600 },
  },
  {
    id: 'search',
    name: 'Suche',
    description: 'Semantisch suchen',
    icon: 'Search',
    color: 'indigo',
    category: 'intelligence',
    defaultSize: { width: 640, height: 500 },
  },
  {
    id: 'timeline',
    name: 'Zeitverlauf',
    description: 'Aktivitäten und Verlauf',
    icon: 'Activity',
    color: 'rose',
    category: 'intelligence',
    defaultSize: { width: 540, height: 620 },
    isNew: true,
  },
  {
    id: 'nightwatch',
    name: 'Nightwatch',
    description: 'MÔRA beobachtet deine Infrastruktur',
    icon: 'ShieldCheck',
    color: 'amber',
    category: 'intelligence',
    defaultSize: { width: 720, height: 640 },
    isNew: true,
  },
  {
    id: 'lagefeld',
    name: 'Lagefeld',
    description: 'Situationsboard — echte Signale aus Mail, Kalender und Môra',
    icon: 'Network',
    color: 'teal',
    category: 'intelligence',
    defaultSize: { width: 1040, height: 720 },
    isNew: true,
  },
  {
    id: 'codex',
    name: 'Engineering',
    description: 'Codex — Agent für Code, Refactors und Systemarbeit',
    icon: 'Bot',
    color: 'indigo',
    category: 'intelligence',
    defaultSize: { width: 900, height: 680 },
    singleton: true,
    requiresRole: ['system_owner', 'owner', 'admin'],
    launcherHidden: true,
  },

  // ── Workspace ─────────────────────────────────────────────────────────────
  {
    id: 'work',
    name: 'Arbeit',
    description: 'Fokussierter Einstieg in Aufgaben, Dateien, Zeit und Kommunikation',
    icon: 'Grid',
    color: 'teal',
    category: 'workspace',
    defaultSize: { width: 1080, height: 760 },
    singleton: true,
    launcherHidden: true,
  },
  {
    id: 'calendar',
    name: 'Kalender',
    description: 'Termine und Ereignisse',
    icon: 'Calendar',
    color: 'green',
    category: 'workspace',
    defaultSize: { width: 840, height: 620 },
  },
  {
    id: 'tasks',
    name: 'Aufgaben',
    description: 'Kanban-Board für Aufgaben',
    icon: 'SquareCheckBig',
    color: 'orange',
    category: 'workspace',
    defaultSize: { width: 900, height: 580 },
    isNew: true,
  },
  {
    id: 'work-session',
    name: 'Arbeitssitzung',
    description: 'Fokussierte Arbeitspläne',
    icon: 'Timer',
    color: 'teal',
    category: 'workspace',
    defaultSize: { width: 640, height: 500 },
  },

  // ── People ────────────────────────────────────────────────────────────────
  {
    id: 'team',
    name: 'Team',
    description: 'Teammitglieder und Aktivität',
    icon: 'Users',
    color: 'blue',
    category: 'people',
    defaultSize: { width: 780, height: 620 },
  },
  {
    id: 'users',
    name: 'Benutzerverwaltung',
    description: 'Benutzer verwalten',
    icon: 'UserCog',
    color: 'slate',
    category: 'people',
    defaultSize: { width: 760, height: 600 },
    requiresRole: ['system_owner', 'owner', 'admin'],
  },

  // ── Productivity ─────────────────────────────────────────────────────────
  {
    id: 'action-center',
    name: 'Action Center',
    description: 'Aktionen, Vorschläge und operative Aufgaben',
    icon: 'Activity',
    color: 'green',
    category: 'core',
    defaultSize: { width: 900, height: 720 },
  },
  {
    id: 'integrations',
    name: 'Integrationen',
    description: 'Verbindungen zu externen Diensten und Plattformen',
    icon: 'Plug',
    color: 'blue',
    category: 'core',
    defaultSize: { width: 860, height: 680 },
  },
  {
    id: 'mail',
    name: 'Mail',
    description: 'E-Mail-Postfach und Kommunikation',
    icon: 'Mail',
    color: 'slate',
    category: 'core',
    defaultSize: { width: 960, height: 680 },
  },
  {
    id: 'feeds',
    name: 'Dein Feed',
    description: 'RSS- und Atom-Quellen mit Vorschaubildern',
    icon: 'Rss',
    color: 'green',
    category: 'core',
    defaultSize: { width: 920, height: 640 },
    isNew: true,
  },

  // ── System ────────────────────────────────────────────────────────────────
  {
    id: 'apps',
    name: 'Apps',
    description: 'App-Bibliothek und Launcher',
    icon: 'Grid',
    color: 'slate',
    category: 'system',
    defaultSize: { width: 900, height: 680 },
  },
  {
    id: 'meine-dateien',
    name: 'Meine Dateien',
    description: 'Persönliche Inhalte und Dateien',
    icon: 'Folder',
    color: 'slate',
    category: 'core',
    defaultSize: { width: 680, height: 560 },
  },
  {
    id: 'terminal',
    name: 'Terminal',
    description: 'Kommandozeile',
    icon: 'Terminal',
    color: 'slate',
    category: 'system',
    defaultSize: { width: 720, height: 480 },
    requiresRole: ['system_owner'],
  },
  {
    id: 'settings',
    name: 'Saimôr Setup',
    description: 'Workspace starten, verbinden und verwalten',
    icon: 'Settings',
    color: 'slate',
    category: 'system',
    defaultSize: { width: 920, height: 700 },
    singleton: true,
  },

  // ── Creative ──────────────────────────────────────────────────────────────
  {
    id: 'canvas',
    name: 'Canvas',
    description: 'Freies Whiteboard',
    icon: 'PenTool',
    color: 'purple',
    category: 'creative',
    defaultSize: { width: 900, height: 660 },
    isNew: true,
  },
];

export function getAppManifest(id: string): AppManifest | undefined {
  return APP_REGISTRY.find(a => a.id === id);
}
