import type { Snapshot } from './types';

// Mock snapshots for Timeline (t0, t1, t2) – Cafe Aurora Demo
// IDs remain stable so selections from Mind Loop can focus nodes across views.
export const mockSnapshots: Snapshot[] = [
  {
    ts: 't0',
    nodes: [
      { id: 'n1', type: 'project', title: 'Cafe Aurora', spaceId: 'cafe-main', tags: ['cafe', 'space'], path: '/Cafe Aurora' },
      { id: 'n2', type: 'document', title: 'Tagesumsatz Montag', spaceId: 'cafe-main', tags: ['umsatz', 'morgen'], path: '/Cafe Aurora/Umsatz/Tagesumsatz-Montag.pdf' },
      { id: 'n3', type: 'note', title: 'Stammgaeste', spaceId: 'cafe-main', tags: ['kunden', 'service'], path: '/Cafe Aurora/Service/Stammgaeste.md' },
    ],
    edges: [
      { sourceId: 'n1', targetId: 'n2', kind: 'contains', weight: 1 },
      { sourceId: 'n1', targetId: 'n3', kind: 'contains', weight: 1 },
    ],
  },
  {
    ts: 't1',
    nodes: [
      { id: 'n1', type: 'project', title: 'Cafe Aurora', spaceId: 'cafe-main', tags: ['cafe', 'space'], path: '/Cafe Aurora' },
      { id: 'n2', type: 'document', title: 'Tagesumsatz Montag', spaceId: 'cafe-main', tags: ['umsatz', 'morgen'], path: '/Cafe Aurora/Umsatz/Tagesumsatz-Montag.pdf' },
      { id: 'n3', type: 'note', title: 'Stammgaeste', spaceId: 'cafe-main', tags: ['kunden', 'service'], path: '/Cafe Aurora/Service/Stammgaeste.md' },
      { id: 'n4', type: 'document', title: 'Feiertag-Umsatz', spaceId: 'cafe-main', tags: ['umsatz', 'special'], path: '/Cafe Aurora/Umsatz/Feiertag-Umsatz.pdf' },
      { id: 'n5', type: 'document', title: 'Kaffee-Sortiment', spaceId: 'cafe-main', tags: ['produkt', 'angebot'], path: '/Cafe Aurora/Sortiment/Kaffee-Sortiment.md' },
    ],
    edges: [
      { sourceId: 'n1', targetId: 'n2', kind: 'contains', weight: 1 },
      { sourceId: 'n1', targetId: 'n3', kind: 'contains', weight: 1 },
      { sourceId: 'n1', targetId: 'n4', kind: 'contains', weight: 1 },
      { sourceId: 'n1', targetId: 'n5', kind: 'contains', weight: 1 },
      { sourceId: 'n2', targetId: 'n4', kind: 'related', weight: 0.6 },
    ],
  },
  {
    ts: 't2',
    nodes: [
      { id: 'n1', type: 'project', title: 'Cafe Aurora', spaceId: 'cafe-main', tags: ['cafe', 'space'], path: '/Cafe Aurora' },
      { id: 'n2', type: 'document', title: 'Tagesumsatz Montag', spaceId: 'cafe-main', tags: ['umsatz', 'morgen'], path: '/Cafe Aurora/Umsatz/Tagesumsatz-Montag.pdf' },
      { id: 'n3', type: 'note', title: 'Stammgaeste', spaceId: 'cafe-main', tags: ['kunden', 'service'], path: '/Cafe Aurora/Service/Stammgaeste.md' },
      { id: 'n4', type: 'document', title: 'Feiertag-Umsatz', spaceId: 'cafe-main', tags: ['umsatz', 'special'], path: '/Cafe Aurora/Umsatz/Feiertag-Umsatz.pdf' },
      { id: 'n5', type: 'document', title: 'Kaffee-Sortiment', spaceId: 'cafe-main', tags: ['produkt', 'angebot'], path: '/Cafe Aurora/Sortiment/Kaffee-Sortiment.md' },
      { id: 'n6', type: 'note', title: 'Schichten-Plan', spaceId: 'cafe-main', tags: ['team', 'planung'], path: '/Cafe Aurora/Team/Schichten-Plan.md' },
      { id: 'n7', type: 'document', title: 'Lieferanten Kaffee', spaceId: 'cafe-main', tags: ['lieferanten', 'produkt'], path: '/Cafe Aurora/Lieferanten/Kaffee.pdf' },
      { id: 'n8', type: 'document', title: 'Rezept Flat White', spaceId: 'cafe-main', tags: ['training', 'qualitaet'], path: '/Cafe Aurora/Rezepte/Flat-White.md' },
      { id: 'n9', type: 'document', title: 'Reinigung Checkliste', spaceId: 'cafe-main', tags: ['betrieb', 'hygiene'], path: '/Cafe Aurora/Betrieb/Reinigung-Checkliste.md' },
      { id: 'n10', type: 'document', title: 'Wochenplanung KW45', spaceId: 'cafe-main', tags: ['planung', 'umsatz'], path: '/Cafe Aurora/Planung/Wochenplanung-KW45.md' },
      { id: 'n11', type: 'insight', title: 'Umsatzpeak Montag Morgen', spaceId: 'cafe-main', tags: ['umsatz', 'trend'], path: '/Cafe Aurora/Insights/Umsatzpeak-Montag' },
      { id: 'n12', type: 'insight', title: 'Milchschaum Qualitaet', spaceId: 'cafe-main', tags: ['qualitaet', 'training'], path: '/Cafe Aurora/Insights/Milchschaum' },
      { id: 'n13', type: 'link', title: 'Bewertungen Google', spaceId: 'cafe-main', tags: ['kunden', 'feedback'], path: 'https://maps.google.com/cafe-aurora' },
      { id: 'n14', type: 'task', title: 'Latte Art Training', spaceId: 'cafe-main', tags: ['training', 'team'], path: '/Cafe Aurora/Team/Latte-Art-Training' },
      { id: 'n15', type: 'document', title: 'Dashboard KPI', spaceId: 'cafe-main', tags: ['report', 'umsatz'], path: '/Cafe Aurora/Reports/Dashboard-KPI.pdf' },
    ],
    edges: [
      { sourceId: 'n1', targetId: 'n2', kind: 'contains', weight: 1 },
      { sourceId: 'n1', targetId: 'n3', kind: 'contains', weight: 1 },
      { sourceId: 'n1', targetId: 'n4', kind: 'contains', weight: 1 },
      { sourceId: 'n1', targetId: 'n5', kind: 'contains', weight: 1 },
      { sourceId: 'n1', targetId: 'n6', kind: 'contains', weight: 1 },
      { sourceId: 'n1', targetId: 'n7', kind: 'contains', weight: 1 },
      { sourceId: 'n1', targetId: 'n8', kind: 'contains', weight: 1 },
      { sourceId: 'n1', targetId: 'n9', kind: 'contains', weight: 1 },
      { sourceId: 'n1', targetId: 'n10', kind: 'contains', weight: 1 },
      { sourceId: 'n1', targetId: 'n11', kind: 'contains', weight: 1 },
      { sourceId: 'n1', targetId: 'n12', kind: 'contains', weight: 1 },
      { sourceId: 'n1', targetId: 'n13', kind: 'contains', weight: 1 },
      { sourceId: 'n1', targetId: 'n14', kind: 'contains', weight: 1 },
      { sourceId: 'n1', targetId: 'n15', kind: 'contains', weight: 1 },
      { sourceId: 'n2', targetId: 'n4', kind: 'related', weight: 0.6 },
      { sourceId: 'n2', targetId: 'n10', kind: 'related', weight: 0.6 },
      { sourceId: 'n2', targetId: 'n11', kind: 'generates', weight: 0.9 },
      { sourceId: 'n3', targetId: 'n13', kind: 'related', weight: 0.5 },
      { sourceId: 'n5', targetId: 'n7', kind: 'supplied_by', weight: 0.7 },
      { sourceId: 'n5', targetId: 'n8', kind: 'details', weight: 0.6 },
      { sourceId: 'n6', targetId: 'n10', kind: 'related', weight: 0.5 },
      { sourceId: 'n6', targetId: 'n14', kind: 'assigned', weight: 0.7 },
      { sourceId: 'n8', targetId: 'n12', kind: 'improves', weight: 0.8 },
      { sourceId: 'n11', targetId: 'n15', kind: 'reports', weight: 0.8 },
      { sourceId: 'n12', targetId: 'n14', kind: 'requires', weight: 0.6 },
    ],
  },
];
