import type { Snapshot } from './types';

// Mock snapshots for Timeline (t0, t1, t2)
export const mockSnapshots: Snapshot[] = [
  {
    ts: 't0',
    nodes: [
      { id: 'n1', type: 'project', title: 'Môra UI', spaceId: 's1', tags: ['active'], path: '/Work/Projects/Môra UI' },
      { id: 'n2', type: 'document', title: 'README.md', spaceId: 's1', tags: ['docs'], path: '/Work/Projects/Môra UI/README.md' },
      { id: 'n3', type: 'document', title: 'QUICKSTART.md', spaceId: 's1', tags: ['docs'], path: '/Work/Projects/Môra UI/QUICKSTART.md' },
    ],
    edges: [
      { sourceId: 'n1', targetId: 'n2', kind: 'contains', weight: 1 },
      { sourceId: 'n1', targetId: 'n3', kind: 'contains', weight: 1 },
    ],
  },
  {
    ts: 't1',
    nodes: [
      { id: 'n1', type: 'project', title: 'Môra UI', spaceId: 's1', tags: ['active'], path: '/Work/Projects/Môra UI' },
      { id: 'n2', type: 'document', title: 'README.md', spaceId: 's1', tags: ['docs'], path: '/Work/Projects/Môra UI/README.md' },
      { id: 'n3', type: 'document', title: 'QUICKSTART.md', spaceId: 's1', tags: ['docs'], path: '/Work/Projects/Môra UI/QUICKSTART.md' },
      { id: 'n4', type: 'code', title: 'app/page.tsx', spaceId: 's1', tags: ['code', 'react'], path: '/Work/Projects/Môra UI/app/page.tsx' },
      { id: 'n5', type: 'code', title: 'components/lens/Lens.tsx', spaceId: 's1', tags: ['code', 'react'], path: '/Work/Projects/Môra UI/components/lens/Lens.tsx' },
    ],
    edges: [
      { sourceId: 'n1', targetId: 'n2', kind: 'contains', weight: 1 },
      { sourceId: 'n1', targetId: 'n3', kind: 'contains', weight: 1 },
      { sourceId: 'n1', targetId: 'n4', kind: 'contains', weight: 1 },
      { sourceId: 'n1', targetId: 'n5', kind: 'contains', weight: 1 },
      { sourceId: 'n2', targetId: 'n3', kind: 'related', weight: 0.5 },
    ],
  },
  {
    ts: 't2',
    nodes: [
      { id: 'n1', type: 'project', title: 'Môra UI', spaceId: 's1', tags: ['active'], path: '/Work/Projects/Môra UI' },
      { id: 'n2', type: 'document', title: 'README.md', spaceId: 's1', tags: ['docs'], path: '/Work/Projects/Môra UI/README.md' },
      { id: 'n3', type: 'document', title: 'QUICKSTART.md', spaceId: 's1', tags: ['docs'], path: '/Work/Projects/Môra UI/QUICKSTART.md' },
      { id: 'n4', type: 'code', title: 'app/page.tsx', spaceId: 's1', tags: ['code', 'react'], path: '/Work/Projects/Môra UI/app/page.tsx' },
      { id: 'n5', type: 'code', title: 'components/lens/Lens.tsx', spaceId: 's1', tags: ['code', 'react'], path: '/Work/Projects/Môra UI/components/lens/Lens.tsx' },
      { id: 'n6', type: 'code', title: 'components/canvas/FieldMode.tsx', spaceId: 's1', tags: ['code', 'react', '3d'], path: '/Work/Projects/Môra UI/components/canvas/FieldMode.tsx' },
      { id: 'n7', type: 'insight', title: 'Field Mode implemented', spaceId: 's1', tags: ['milestone'], path: '/Insights/Field Mode' },
      { id: 'n8', type: 'code', title: 'lib/api.ts', spaceId: 's1', tags: ['code', 'api'], path: '/Work/Projects/Môra UI/lib/api.ts' },
      { id: 'n9', type: 'code', title: 'lib/types.ts', spaceId: 's1', tags: ['code', 'types'], path: '/Work/Projects/Môra UI/lib/types.ts' },
      { id: 'n10', type: 'document', title: 'ARCHITECTURE.md', spaceId: 's1', tags: ['docs', 'design'], path: '/Work/Projects/Môra UI/ARCHITECTURE.md' },
      { id: 'n11', type: 'code', title: 'components/insights/Insights.tsx', spaceId: 's1', tags: ['code', 'react'], path: '/Work/Projects/Môra UI/components/insights/Insights.tsx' },
      { id: 'n12', type: 'code', title: 'components/canvas/Canvas.tsx', spaceId: 's1', tags: ['code', 'react'], path: '/Work/Projects/Môra UI/components/canvas/Canvas.tsx' },
      { id: 'n13', type: 'insight', title: 'UI/Core integration stable', spaceId: 's1', tags: ['milestone'], path: '/Insights/Integration' },
      { id: 'n14', type: 'document', title: 'UI_MASTER.md', spaceId: 's1', tags: ['docs', 'guide'], path: '/Work/Projects/Môra UI/UI_MASTER.md' },
      { id: 'n15', type: 'code', title: 'lib/config.ts', spaceId: 's1', tags: ['code', 'config'], path: '/Work/Projects/Môra UI/lib/config.ts' },
    ],
    edges: [
      { sourceId: 'n1', targetId: 'n2', kind: 'contains', weight: 1 },
      { sourceId: 'n1', targetId: 'n3', kind: 'contains', weight: 1 },
      { sourceId: 'n1', targetId: 'n4', kind: 'contains', weight: 1 },
      { sourceId: 'n1', targetId: 'n5', kind: 'contains', weight: 1 },
      { sourceId: 'n1', targetId: 'n6', kind: 'contains', weight: 1 },
      { sourceId: 'n1', targetId: 'n8', kind: 'contains', weight: 1 },
      { sourceId: 'n1', targetId: 'n9', kind: 'contains', weight: 1 },
      { sourceId: 'n1', targetId: 'n10', kind: 'contains', weight: 1 },
      { sourceId: 'n1', targetId: 'n11', kind: 'contains', weight: 1 },
      { sourceId: 'n1', targetId: 'n12', kind: 'contains', weight: 1 },
      { sourceId: 'n1', targetId: 'n14', kind: 'contains', weight: 1 },
      { sourceId: 'n1', targetId: 'n15', kind: 'contains', weight: 1 },
      { sourceId: 'n2', targetId: 'n3', kind: 'related', weight: 0.5 },
      { sourceId: 'n2', targetId: 'n10', kind: 'related', weight: 0.6 },
      { sourceId: 'n4', targetId: 'n5', kind: 'imports', weight: 0.8 },
      { sourceId: 'n4', targetId: 'n6', kind: 'imports', weight: 0.8 },
      { sourceId: 'n4', targetId: 'n12', kind: 'imports', weight: 0.8 },
      { sourceId: 'n5', targetId: 'n9', kind: 'imports', weight: 0.7 },
      { sourceId: 'n6', targetId: 'n7', kind: 'generates', weight: 1 },
      { sourceId: 'n6', targetId: 'n9', kind: 'imports', weight: 0.7 },
      { sourceId: 'n8', targetId: 'n9', kind: 'imports', weight: 0.9 },
      { sourceId: 'n8', targetId: 'n15', kind: 'imports', weight: 0.8 },
      { sourceId: 'n11', targetId: 'n8', kind: 'imports', weight: 0.7 },
      { sourceId: 'n12', targetId: 'n6', kind: 'imports', weight: 0.8 },
      { sourceId: 'n13', targetId: 'n8', kind: 'validates', weight: 1 },
      { sourceId: 'n14', targetId: 'n10', kind: 'extends', weight: 0.6 },
      { sourceId: 'n15', targetId: 'n13', kind: 'enables', weight: 0.9 },
    ],
  },
];
